### ISSUE TITLE
opencv branch

### ISSUE THREAD

**Issue by BrookRoberts** [paulinus/opensfm-docker-base#1]
Is there any reason the opencv branch is not in master?  I'm presuming that opensfm won't run without opencv, and having tested the opencv branch here and building a docker image, it seems that at least for standard runs of opensfm the docker image on opencv branch works.

**Comment by paulinus** [comment]
The `opencv3` branch installs OpenCV version 3. `master` uses OpenCV version 2 provided by ubuntu packages.

**Comment by BrookRoberts** [comment]
Ah, sorry, being dopey, didn't see that it still installed OpenCV.  Seems to work fine with opencv3 though!
