### ISSUE TITLE
How to run this docker file.?

### ISSUE THREAD

**Issue by DRAhmadFaraz** [paulinus/opensfm-docker-base#3]
@paulinus  Sorry for basic Question, as I am new on Docker and I want to install all the dependencies by using this docker file, So please guide me how to run this file on Ubuntu.?

**Comment by houhaol** [comment]
Have you fixed it?

**Comment by paulinus** [comment]
You should not need to use this repository. It is only meant to be an example of how to install the dependencies in Ubuntu. So having a look at `https://github.com/paulinus/opensfm-docker-base/blob/master/Dockerfile` one can see a way to install the dependencies.
