### ISSUE TITLE
python3 docker base

### ISSUE THREAD

**Issue by CorentinLemaitre** [paulinus/opensfm-docker-base#4]
Hello i use windows 10 docker to run OpenSfM. 

My issue : the program want to run with python 3 and it is not in the docker.
I have install the docker image : `docker pull paulinus/opensfm-docker-base`
Then i did run it : `docker run -it paulinus/opensfm-docker-base` 

Then i have try to build OpenSfM and use the berlin data.
```
git clone --recursive https://github.com/mapillary/OpenSfM
cd OpenSfM
python setup.py build
bin/opensfm_run_all data/berlin
```
the result : 
```
Running using Python command: python3
bin/opensfm_run_all: line 10: python3: command not found
```
I have see in the current repo that there is dockerfile for python 2 and python 3 but i have no idea how to use it.

**Comment by CorentinLemaitre** [comment]
I did manage to solve part of this. 
I have download the file `Dockerfile.python3`
I have rename it `Dockerfile`
Then i build an image with the command `docker build -t my_docker .`

Then i run it : 
```
docker run -it -p 8000:8000 --name my_opensfm my_docker
git clone --recursive https://github.com/mapillary/OpenSfM
cd OpenSfM
python3 setup.py build
cd doc
pip3 install sphinx
pip3 install sphinx_rtd_theme
make livehtml
pip3 install joblib
bin/opensfm_run_all data/berlin
python3 -m http.server 8000
```
The packages intalled with pip3 was missing and are may be usefull to add in the dockerfile.

**Comment by paulinus** [comment]
Hey, @CorentinLemaitre, you don't need to use this repository directly.
You can build the opensfm docker image by running this from the opensfm folder:
```
docker build -t my_opensfm -f Dockerfile .
```

And then this to run it:
```
docker run -ti my_opensfm
````
